# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 07:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180125_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
