# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180126_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='follows',
            field=models.ManyToManyField(
                related_name='followed_by', to='user_profile.User_details'),
        ),
    ]
