# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_user_details_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
