# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_user_details_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='file',
            field=models.ImageField(null=True, upload_to='profile_photos'),
        ),
    ]
