# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20180129_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to='photos')),
            ],
            options={
                'verbose_name': 'photo',
            },
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='profile_photo',
        ),
    ]
