# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 08:20
from __future__ import unicode_literals

from django.db import migrations, models

import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.AddField(
            model_name='user_details',
            name='cover_photo',
            field=models.ImageField(
                null=True, upload_to=user_profile.models.upload_posts_media_to),
        ),
        migrations.AddField(
            model_name='user_details',
            name='profile_photo',
            field=models.ImageField(
                null=True, upload_to=user_profile.models.upload_posts_media_to),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
