# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20180202_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='cover_photo',
            field=models.ImageField(default=None, upload_to=user_profile.models.upload_posts_media_to),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to=user_profile.models.upload_posts_media_to),
        ),
    ]
