# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20180202_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='gender',
            field=models.CharField(choices=[(None, None), ('M', 'Male'), ('F', 'Female')], max_length=2, null=True),
        ),
    ]
