# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20180210_1826'),
        ('user_profile', '0013_auto_20180210_1746'),
    ]

    operations = [
    ]
