# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 02:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20180224_1432'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set([('post', 'user')]),
        ),
    ]
