# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180308_0257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set([]),
        ),
    ]
