# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 18:26
from __future__ import unicode_literals

from django.db import migrations, models

import posts.model_validators
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180209_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media',
            field=models.FileField(upload_to=posts.models.upload_posts_media_to, validators=[
                                   posts.model_validators.validate_file_extension_posts_media]),
        ),
    ]
