# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_tag_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media',
            field=models.ImageField(upload_to=posts.models.upload_posts_media_to),
        ),
    ]
